spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/movie_review_dev}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ${SECRET:defaultSecretKeyForDevelopmentOnly1234567890!}
  expiration: 360000